// <auto-generated />
using System;
using KSProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KSProject.Infrastructure.Migrations
{
    [DbContext(typeof(KSProjectDbContext))]
    [Migration("20251113184025_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KSProject.Domain.Aggregates.Billings.ServiceRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("RatePerUnit")
                        .HasColumnType("numeric");

                    b.Property<string>("RulesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ServiceType", "MetricType", "Variant")
                        .IsUnique();

                    b.ToTable("ServiceRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "Posts_Count",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            RatePerUnit = 0.01m,
                            ServiceType = "Blog",
                            Variant = "Default",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-4444-5555-666666666666"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "Posts_Count",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            RatePerUnit = 0.005m,
                            RulesJson = "{\"minQuantity\": 50, \"discountPercent\": 10}",
                            ServiceType = "Blog",
                            Variant = "Premium",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-5555-6666-777777777777"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "SMS_Count",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            RatePerUnit = 0.02m,
                            ServiceType = "Notification",
                            Variant = "Default",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("44444444-5555-6666-7777-888888888888"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "Transactions_Count",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            RatePerUnit = 0.015m,
                            RulesJson = "{\"minQuantity\": 100, \"discountPercent\": 15}",
                            ServiceType = "OnlineStore",
                            Variant = "Tier1",
                            Version = 1L
                        });
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98f4f7df-15bb-4547-8495-f098a753536f"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Administrator role with all permissions.",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            Name = "Admin",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("1fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Standard user role with limited permissions.",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            Name = "User",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("3fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Test Role to test soft delete",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            Name = "TestRole",
                            Version = 1L
                        });
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Roles.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Test.TestAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TestAggregates");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Test.TestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("TestAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestAggregateId");

                    b.ToTable("TestEntities");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Users.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c55fb374-3d74-4aa3-b576-d144c49cd184"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            ExpirationDate = new DateTime(2026, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Key = "c55fb3743d744aa3b576d144c49cd184",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            Scopes = "sliders.create,sliders.show-all,sliders.update,users.show-all,users.create,users.update,users.delete",
                            UserId = new Guid("551de0bd-f8bf-4fa4-9523-f19b7c6dd95b"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("0acc9f75-9201-4ea5-9a16-5be1c30d6f60"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            ExpirationDate = new DateTime(2026, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Key = "0acc9f7592014ea59a165be1c30d6f60",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            Scopes = "sliders.create,sliders.show-all,sliders.update,users.show-all,users.create,users.update,users.delete",
                            UserId = new Guid("5d2b2a64-0fa7-46af-bf1c-aadf1d7fb120"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("ed12b679-8fd0-4a0c-ade5-fa6aaccf42fd"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            ExpirationDate = new DateTime(2026, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Key = "ed12b6798fd04a0cade5fa6aaccf42fd",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            Scopes = "sliders.show-all",
                            UserId = new Guid("c75e1cf0-84c0-4f9e-a608-e9a9b0e7d62f"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("17f9e83c-b763-4e38-8902-1d0583adab05"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            ExpirationDate = new DateTime(2026, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Key = "17f9e83cb7634e3889021d0583adab05",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            Scopes = "sliders.create,sliders.show-all",
                            UserId = new Guid("c75e1cf0-84c0-4f9e-a608-e9a9b0e7d62f"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("2a5018f6-c8db-490a-9707-221469d20bb7"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            ExpirationDate = new DateTime(2026, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Key = "2a5018f6c8db490a9707221469d20bb7",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            Scopes = "sliders.create,sliders.show-all",
                            UserId = new Guid("2fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("WalletId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("551de0bd-f8bf-4fa4-9523-f19b7c6dd95b"),
                            Active = true,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "superadmin@superadmin.com",
                            HashedPassword = "01cVBRfT5lroSYX3twWtmf3Dg3KiLs6gzsr4qvggokk=",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            PhoneNumber = "09123456780",
                            SuperAdmin = true,
                            UserName = "superadmin",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("5d2b2a64-0fa7-46af-bf1c-aadf1d7fb120"),
                            Active = true,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "admin@admin.com",
                            HashedPassword = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            PhoneNumber = "09123456789",
                            SuperAdmin = false,
                            UserName = "admin",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("c75e1cf0-84c0-4f9e-a608-e9a9b0e7d62f"),
                            Active = true,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "user1@user.com",
                            HashedPassword = "vFhI8ifMFh619o3+mMsTEQqchDzmnpU6iBB9hlWD05c=",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            PhoneNumber = "09123456782",
                            SuperAdmin = false,
                            UserName = "user1",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("9650f7f3-333b-4a77-b992-9a55179bfa12"),
                            Active = true,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "user2@user.com",
                            HashedPassword = "vFhI8ifMFh619o3+mMsTEQqchDzmnpU6iBB9hlWD05c=",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            PhoneNumber = "09123456787",
                            SuperAdmin = false,
                            UserName = "user2",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("2fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            Active = true,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "test@user.com",
                            HashedPassword = "vFhI8ifMFh619o3+mMsTEQqchDzmnpU6iBB9hlWD05c=",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            PhoneNumber = "09123456783",
                            SuperAdmin = false,
                            UserName = "test",
                            Version = 1L
                        });
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec7a3150-c202-4895-8b00-232f28e0eb4f"),
                            AboutMe = "This is SuperAdmin Profile",
                            BirthDate = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FirstName = "Super",
                            IsDeleted = false,
                            LastName = "Admin",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ProfileImageUrl = "/image.png",
                            UserId = new Guid("551de0bd-f8bf-4fa4-9523-f19b7c6dd95b"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("5e46e00a-5162-4417-a240-36dc48793ad5"),
                            AboutMe = "This is Admin Profile",
                            BirthDate = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "User",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ProfileImageUrl = "/image.png",
                            UserId = new Guid("5d2b2a64-0fa7-46af-bf1c-aadf1d7fb120"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("b21013eb-7182-46ef-b543-b9606bc45c83"),
                            AboutMe = "This is User One Profile",
                            BirthDate = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FirstName = "User",
                            IsDeleted = false,
                            LastName = "One",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ProfileImageUrl = "/image.png",
                            UserId = new Guid("c75e1cf0-84c0-4f9e-a608-e9a9b0e7d62f"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("29a0421c-6e4e-4793-bf3d-aad975155381"),
                            AboutMe = "This is User Two Profile",
                            BirthDate = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FirstName = "User",
                            IsDeleted = false,
                            LastName = "Two",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ProfileImageUrl = "/image.png",
                            UserId = new Guid("9650f7f3-333b-4a77-b992-9a55179bfa12"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("445819eb-053a-4c13-b8dd-fb736d46739f"),
                            AboutMe = "This is User Test Profile",
                            BirthDate = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FirstName = "Test",
                            IsDeleted = false,
                            LastName = "User",
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ProfileImageUrl = "/image.png",
                            UserId = new Guid("2fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Wallets.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricDetails")
                        .HasColumnType("text");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-def234567890"),
                            Amount = 100.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "",
                            MetricValue = 0m,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ServiceType = "",
                            TransactionDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Charge",
                            Version = 1L,
                            WalletId = new Guid("c55fb374-3d74-4aa3-b576-d144c49cd184")
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f678-9abc-1def-234567890abc"),
                            Amount = -5.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "Posts_Count",
                            MetricValue = 5.0m,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ServiceType = "Blog",
                            TransactionDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Usage",
                            Version = 1L,
                            WalletId = new Guid("c55fb374-3d74-4aa3-b576-d144c49cd184")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-789a-bc1d-ef23-4567890abcde"),
                            Amount = 50.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "",
                            MetricValue = 0m,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ServiceType = "",
                            TransactionDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Charge",
                            Version = 1L,
                            WalletId = new Guid("0acc9f75-9201-4ea5-9a16-5be1c30d6f60")
                        },
                        new
                        {
                            Id = new Guid("d4e5f678-9abc-1def-2345-67890abcde12"),
                            Amount = -2.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "SMS_Count",
                            MetricValue = 10.0m,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ServiceType = "Notification",
                            TransactionDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Usage",
                            Version = 1L,
                            WalletId = new Guid("ed12b679-8fd0-4a0c-ade5-fa6aaccf42fd")
                        },
                        new
                        {
                            Id = new Guid("e5f6789a-bc1d-ef23-4567-890abcde1234"),
                            Amount = 10.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "Transactions_Count",
                            MetricValue = 1.0m,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ServiceType = "OnlineStore",
                            TransactionDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Refund",
                            Version = 1L,
                            WalletId = new Guid("17f9e83c-b763-4e38-8902-1d0583adab05")
                        },
                        new
                        {
                            Id = new Guid("f6789abc-1def-2345-6789-0abcde123456"),
                            Amount = -1.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            MetricType = "",
                            MetricValue = 0m,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            ServiceType = "",
                            TransactionDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Adjustment",
                            Version = 1L,
                            WalletId = new Guid("2a5018f6-c8db-490a-9707-221469d20bb7")
                        });
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Wallets.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c55fb374-3d74-4aa3-b576-d144c49cd184"),
                            Balance = 100.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            UserId = new Guid("551de0bd-f8bf-4fa4-9523-f19b7c6dd95b"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("0acc9f75-9201-4ea5-9a16-5be1c30d6f60"),
                            Balance = 50.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            UserId = new Guid("5d2b2a64-0fa7-46af-bf1c-aadf1d7fb120"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("ed12b679-8fd0-4a0c-ade5-fa6aaccf42fd"),
                            Balance = 20.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            UserId = new Guid("c75e1cf0-84c0-4f9e-a608-e9a9b0e7d62f"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("17f9e83c-b763-4e38-8902-1d0583adab05"),
                            Balance = 0.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            UserId = new Guid("9650f7f3-333b-4a77-b992-9a55179bfa12"),
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("2a5018f6-c8db-490a-9707-221469d20bb7"),
                            Balance = 10.0m,
                            CreatedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "System",
                            UserId = new Guid("2fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("KSProject.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OccuredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("UsersRoles", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UsersRoles");

                    b.HasData(
                        new
                        {
                            RolesId = new Guid("1fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            UsersId = new Guid("551de0bd-f8bf-4fa4-9523-f19b7c6dd95b")
                        },
                        new
                        {
                            RolesId = new Guid("98f4f7df-15bb-4547-8495-f098a753536f"),
                            UsersId = new Guid("5d2b2a64-0fa7-46af-bf1c-aadf1d7fb120")
                        },
                        new
                        {
                            RolesId = new Guid("1fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            UsersId = new Guid("c75e1cf0-84c0-4f9e-a608-e9a9b0e7d62f")
                        },
                        new
                        {
                            RolesId = new Guid("1fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            UsersId = new Guid("9650f7f3-333b-4a77-b992-9a55179bfa12")
                        },
                        new
                        {
                            RolesId = new Guid("3fd5d547-737a-45d3-b71f-c5e8f692d434"),
                            UsersId = new Guid("2fd5d547-737a-45d3-b71f-c5e8f692d434")
                        });
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Roles.RolePermission", b =>
                {
                    b.HasOne("KSProject.Domain.Aggregates.Roles.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Test.TestEntity", b =>
                {
                    b.HasOne("KSProject.Domain.Aggregates.Test.TestAggregate", "TestAggregate")
                        .WithMany("Entities")
                        .HasForeignKey("TestAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestAggregate");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Users.ApiKey", b =>
                {
                    b.HasOne("KSProject.Domain.Aggregates.Users.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Users.User", b =>
                {
                    b.HasOne("KSProject.Domain.Aggregates.Wallets.Wallet", "Wallet")
                        .WithOne()
                        .HasForeignKey("KSProject.Domain.Aggregates.Users.User", "WalletId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("KSProject.Domain.Aggregates.Users.ValueObjects.UserLoginDate", "UserLoginDates", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("LoginDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserLoginDates", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("KSProject.Domain.Aggregates.Users.ValueObjects.UserPermission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserPermissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("KSProject.Domain.Aggregates.Users.ValueObjects.UserSecurityStamp", "UserSecurityStamps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("ExpirationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SecurityStamp")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserSecurityStamps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("KSProject.Domain.Aggregates.Users.ValueObjects.UserToken", "UserTokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpirationDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Permissions");

                    b.Navigation("UserLoginDates");

                    b.Navigation("UserSecurityStamps");

                    b.Navigation("UserTokens");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Users.UserProfile", b =>
                {
                    b.HasOne("KSProject.Domain.Aggregates.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("KSProject.Domain.Aggregates.Users.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Wallets.Transaction", b =>
                {
                    b.HasOne("KSProject.Domain.Aggregates.Wallets.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("UsersRoles", b =>
                {
                    b.HasOne("KSProject.Domain.Aggregates.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KSProject.Domain.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Roles.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Test.TestAggregate", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("KSProject.Domain.Aggregates.Wallets.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
